"""Add separate fields for dual track outputs

Revision ID: 3856cf9ae086
Revises: 6e573f0edec3
Create Date: 2025-06-22 07:33:16.381567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3856cf9ae086'
down_revision: Union[str, None] = '6e573f0edec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.add_column('drawings', sa.Column('s3_key', sa.String(), nullable=True))
    op.add_column('drawings', sa.Column('s3_url', sa.String(), nullable=True))
    op.add_column('drawings', sa.Column('s3_bucket', sa.String(), nullable=True))
    op.add_column('drawings', sa.Column('ocr_recognition_display', sa.JSON(), nullable=True))
    op.add_column('drawings', sa.Column('quantity_list_display', sa.JSON(), nullable=True))
    op.add_column('drawings', sa.Column('quantity_results', sa.JSON(), nullable=True))
    op.add_column('drawings', sa.Column('processing_result', sa.JSON(), nullable=True))
    op.add_column('drawings', sa.Column('components_count', sa.Integer(), nullable=True))
    op.add_column('drawings', sa.Column('celery_task_id', sa.String(), nullable=True))
    op.add_column('drawings', sa.Column('s3_urls', sa.JSON(), nullable=True))
    op.alter_column('drawings', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drawings', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drawings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('drawings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_drawings_filename', table_name='drawings')
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'full_name')
    op.create_index('ix_drawings_filename', 'drawings', ['filename'], unique=False)
    op.alter_column('drawings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('drawings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('drawings', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drawings', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('drawings', 's3_urls')
    op.drop_column('drawings', 'celery_task_id')
    op.drop_column('drawings', 'components_count')
    op.drop_column('drawings', 'processing_result')
    op.drop_column('drawings', 'quantity_results')
    op.drop_column('drawings', 'quantity_list_display')
    op.drop_column('drawings', 'ocr_recognition_display')
    op.drop_column('drawings', 's3_bucket')
    op.drop_column('drawings', 's3_url')
    op.drop_column('drawings', 's3_key')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
