"""Create initial tables

Revision ID: 4d23052f2c95
Revises: 
Create Date: 2024-03-25 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d23052f2c95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drawings', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drawings', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drawings', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('drawings', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('drawings', sa.Column('ocr_results', sa.JSON(), nullable=True))
    op.add_column('drawings', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawings', 'task_id')
    op.drop_column('drawings', 'ocr_results')
    op.drop_column('drawings', 'error_message')
    op.alter_column('drawings', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drawings', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drawings', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
